# List of PHP sockets
upstream php_sockets {
	# [OPTION] Specify PHP version for Socket.
	# Support from https://www.php.net/supported-versions.php

	# Option 1. [DEFAULT] PHP 8.5
	# Supported until 2028-11-21
	server unix:/var/run/php/php8.5-fpm.sock;

	# Option 2. [DISABLED] PHP 8.4
	# Supported until 2027-11-20
	#server unix:/var/run/php/php8.4-fpm.sock;

	# Option 3. [DISABLED] PHP 8.3
	# Supported until 2026-11-23
	#server unix:/var/run/php/php8.3-fpm.sock;

	# Option 4. [DISABLED] PHP 8.2
	# Supported until 2025-12-31
	#server unix:/var/run/php/php8.2-fpm.sock;

	# [OPTION] Specify backup socket for PHP.
	#server unix:/var/run/php/php8.5-fpm.sock backup;

}
