# eustasy/.Normal 4.0beta16
name: "Normal: Actions"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
      - ".github/zizmor.yml"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"
      - ".github/zizmor.yml"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  actions:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/actions@v4
