# eustasy/.Normal 4.0beta8
name: Normal (CSS/SCSS)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ["**.css", "**.scss"]
  pull_request:
    branches: [main]
    paths: ["**.css", "**.scss"]

permissions:
  contents: read

jobs:
  css:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: qltysh/qlty-action/install@fd52dc852530a708d68c3b7342f8d33d1df4cd55 # v2.2.1

      - name: Lint + format check (stylelint)
        run: qlty check --all --filter=stylelint
