# eustasy/.Normal 4.0beta16
name: "Normal: CSS/SCSS"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.css"
      - "**.scss"
      - ".github/workflows/css.yml"
      - ".qlty/configs/.stylelintrc.json"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.css"
      - "**.scss"
      - ".github/workflows/css.yml"
      - ".qlty/configs/.stylelintrc.json"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  css:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/css@v4
