# eustasy/.Normal 4.0beta13
name: "Normal: HTML"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.html"
      - "**.htm"
      - ".github/workflows/html.yml"
      - ".qlty/configs/.htmlvalidate.json"
  pull_request:
    branches: [main]
    paths:
      - "**.html"
      - "**.htm"
      - ".github/workflows/html.yml"
      - ".qlty/configs/.htmlvalidate.json"

permissions:
  contents: read

jobs:
  html:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/html@v4
