# eustasy/.Normal 4.0beta16
name: "Normal: JS / TS"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.js"
      - "**.ts"
      - "**.mjs"
      - "**.cjs"
      - "**.mts"
      - "**.cts"
      - ".github/workflows/js.yml"
      - ".qlty/configs/oxlint.json"
      - ".qlty/configs/.prettierrc.json"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.js"
      - "**.ts"
      - "**.mjs"
      - "**.cjs"
      - "**.mts"
      - "**.cts"
      - ".github/workflows/js.yml"
      - ".qlty/configs/oxlint.json"
      - ".qlty/configs/.prettierrc.json"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  js:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/js@v4
