# eustasy/.Normal 4.0beta13
name: "Normal: JSON"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.json"
      - ".github/workflows/json.yml"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.json"
      - ".github/workflows/json.yml"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  json:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/json@v4
