# eustasy/.Normal 4.0beta16
name: "Normal: Markdown"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.md"
      - ".github/workflows/md.yml"
      - ".qlty/configs/.markdownlint.json"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.md"
      - ".github/workflows/md.yml"
      - ".qlty/configs/.markdownlint.json"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  md:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/md@v4
