name: Normal

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  normal-tests:
    strategy:
      matrix:
        php-version: [ "8.2", "8.1", "8.0", "7.4" ]
    runs-on: ubuntu-latest
    steps:
    
    - name: Install PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        #extensions: mbstring
        
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        # Version Spec of the version to use in SemVer notation.
        # It also emits such aliases as lts, latest, nightly and canary builds
        # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
        node-version: 'lts/*'
        # Set this option if you want the action to check for the latest available version 
        # that satisfies the version spec.
        # It will only get affect for lts Nodejs versions (12.x, >=10.15.0, lts/Hydrogen). 
        # Default: false
        check-latest: true
        
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: .Normal - Setup
      run: git clone https://github.com/eustasy/.normal.git && cd .normal && git checkout af240a6c8960177bcb1d07815732df7eb15970c1 && cd ../ && npm install --silent -g npm && npm install --silent -g acorn
      
    - name: .Normal - Check JavaScript
      run: ./.normal/check-javascript.sh
      
    - name: .Normal - Check PHP
      run: ./.normal/check-php.sh
      
    - name: .Normal - Check SQL
      uses: Bidaya0/sql-lint-in-action@v0.0.2
      
    - name: .Normal - Check JSON
      run: php .normal/check-json.php
      
    - name: .Normal - Check XML
      run: php .normal/check-xml.php
