# eustasy/.Normal 4.0beta16
name: "Normal: Shell"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.sh"
      - ".github/workflows/sh.yml"
      - ".qlty/qlty.toml"
  pull_request:
    branches: [main]
    paths:
      - "**.sh"
      - ".github/workflows/sh.yml"
      - ".qlty/qlty.toml"

permissions:
  contents: read

jobs:
  sh:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: eustasy/.normal/sh@v4
