# eustasy/.Normal 4.0beta1
name: SQL

on:
  push:
    branches: [main]
    paths: ["**.sql"]
  pull_request:
    branches: [main]
    paths: ["**.sql"]

permissions:
  contents: read

jobs:
  sql:
    name: Lint + format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: qltysh/qlty-action/install@v2

      - name: Lint + format check (sqlfluff)
        run: qlty check --all --filter=sqlfluff
